#include<iostream>
#include<cstdlib>
#include<ctime>//using device time
using namespace std;

int main()
    {
    	int n;
    	cout<<"Enter the length of password :";
    	cin>>n;
	    srand(time(0));
	    string password;
	    string values="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789~`!@#$%^&*()-_=+|\{}[];:,.<>";
			for(int i=1;i<=n;i++)
			{
				password=password+values[rand()%93];    
			}     
		cout<<"Your generated password of length "<<n<<" is: "<<password;
		return 0;
   
	}
	
	/*time(0) returns the amount of seconds that have passed since that moment.
	srand(time(0)) is used in C++ to help in the generation of random numbers 
	by seeding rand with a starting value.*/
	
	/*rand() function is an inbuilt function in C++ STL,which is defined in 
	header file <cstdlib>.rand() is used to generate a series of random numbers.
	The random number is generated by using an algorithm that gives a series 
	of non-related numbers whenever this function is called.*/ 	
	
	
